### ISSUE TITLE
Typos/errors in test. Solution already in index.js

### ISSUE THREAD

**Issue by MarSchlaefer** [learn-co-curriculum/fewpjs_destructuring_assignment#3]
- last test: song_2 is defined as the incorrect song
- last const destructuring lines in index.js file should be:
const { song_2, song_4} = k_muppet.k_album.the_muppet_movie
const { k_color, k_job, k_partner } = k_muppet
- solution already in index.js so students dont have to do any work on their own.

#staff

**Comment by sgharms** [comment]
@MarSchlaefer I think i've cleaned this up: `master` is cleaned up and is passable with `solution`'s code. If it's OK, please close.
