### ISSUE TITLE
The destructuring with objects (and nested objects) needs a little more clarity

### ISSUE THREAD

**Issue by merecka** [learn-co-curriculum/fewpjs_destructuring_assignment#4]
I found test #8 in the lab quite difficult to do mainly because the reading on destructuring with objects and nested objects in the lesson wasn't very clear.  Specifically, it does not state that the values inside of the `const` for the destructuring objects have to exactly match the key names in those object.  While the examples do use the exact key names, it is not explicitly stated that it has to be done this way so the reader doesn't really know if this was intentional or just a coincidence.  What really makes this even more confusing for a first-timer (like myself) is that the lab then goes on to talk about destructuring with arrays where the variable names in the `const` can be arbitrary since they refer to the index numbers.  A sentence or two stating that the variable names in the `const` need to match the key names in the objects that are being deconstructed would be very helpful.

Also, it was not clear to me that I didn't have to account for unused object keys in my deconstructor like you have to do with arrays.  I think just a little more clarity on this would be worthwhile even if it lengthens the reading a bit.

**Comment by sgharms** [comment]
good point. Change made.
