### ISSUE TITLE
Running learn in WSL Terminal Error

### ISSUE THREAD

**Issue by webdevjscoder** [learn-co-curriculum/fewpjs_destructuring_assignment#8]
I am using the WSL terminal when I run learn for the test suites. I receive this error:

Traceback (most recent call last):
        11: from /home/jcobian/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
        10: from /home/jcobian/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
         9: from /home/jcobian/.rvm/gems/ruby-2.6.1/bin/learn-test:23:in `<main>'
         8: from /home/jcobian/.rvm/gems/ruby-2.6.1/bin/learn-test:23:in `load'
         7: from /home/jcobian/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/bin/learn-test:68:in `<top (required)>'
         6: from /home/jcobian/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in `run'
         5: from /home/jcobian/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in `fork'
         4: from /home/jcobian/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:21:in `block in run'
         3: from /home/jcobian/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:44:in `report_and_clean'
         2: from /home/jcobian/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:13:in `report'
         1: from /home/jcobian/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:47:in `report'
/home/jcobian/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/strategies/mocha.rb:42:in `results': undefined method `[]' for nil:NilClass (NoMethodError)

It runs fine at first by this I mean it'll work then out of nowhere it gives me this error. This is not the first time I've into this issue, the first time I deleted the forked copy and re-forked. One of my cohort members than ran into the same issue and found a solution:

Run
  rm -rf node_modules

Then run
  npm install node

This worked the first couple of times after I kept running into this issue but now it's not working and I had to revert back to deleting the forked repo and forking it again.

**Comment by webdevjscoder** [comment]
I figured out why the error happens. Its because the test fails but it breaks the test suites, almost like it doesn't know how to render the error properly and just breaks.

**Comment by lizbur10** [comment]
Hi there! I'm going to close this issue since you were able to resolve it.

Thanks 💙
