### ISSUE TITLE
Misc improvements

### ISSUE THREAD

**Issue by spenser6131** [learn-co-curriculum/fewpjs_destructuring_assignment#9]
In the section "Destructuring Assignment with Strings", the code snippet defines a variable which it doesn't end up using. This snippet would be more effective if it did utilize the variable it defines.

Here's the snippet, which defines dogsName on the first line and _should_ but doesn't reference on the second line:
```
const dogsName = 'Sir Woody BarksALot'
const [title, firstName, lastName] = 'Sir Woody BarksALot'.split(' ')
console.log(title, firstName, lastName) // Sir Woody BarksALot
```
The same goes for the snippet immediately after.

<br><br>
Additionally, in `index.js`, step number 8 asks "Use destructuring to assign songs 2 and 4, and Kermit's job and partner" but the spec checks for these variables as well as **_color_**.

**Comment by lizbur10** [comment]
Hi there! Thanks for posting this issue - the lesson has been updated to address these points.

Thank you for contributing to the Flatiron School curriculum 💙
